{{- if.Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-web.fullname" . }}-secret-env
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range .Values.secret }}
  {{ .name }}: {{ .value }}
  {{- end }}
{{- end }}

{{- if .Values.secretFiles }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-web.fullname" . }}-secret-files
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range .Values.secretFiles }}
  {{ .name }}: {{ .data }}
  {{- end }}
{{- end }}
